# Generated by Django 4.1.5 on 2023-02-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='reader_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
